name: expdecay1000
modes: ["expdecay"] # list of scheduler to use
kwargs:
  # all kwargs
  expdecay:
    decay_factor: 1000 # by how much to reduce lr during training
    epochs: ${trainer.max_epochs}