name: plateau_quick
modes: ["ReduceLROnPlateau"] # list of scheduler to use
kwargs:
  # all kwargs
  ReduceLROnPlateau:
    mode: min 
    factor: 0.3  # factor by wich to reduce lr
    patience: 5  # number of epochs with no improvement after which learning rate will be reduce
    threshold: 0.0001 # threshold to be considered "better"
    threshold_mode: rel # relative threshold instead of avsolute
    verbose: True
    min_lr: 1e-7 # minimum learning reate
    kwargs_config_scheduler:
      monitor: ${checkpoint.kwargs.monitor}