# @package _global_
defaults:
  - base@rate
  
rate:
  kwargs:
    n_z_samples: ${featurizer.loss.n_z_samples}
    invertible_processing: diag
    kwargs_ent_bottleneck:
      init_scale: 10 # input should be at initialization in [-init_scale, init_scale]. Larger might create overhead. You can use something like 10 for large images but smaller for smaller 
      filters: [3, 3, 3, 3] # size of the entropy model (quite robust to that)
    
encoder:
  fam: deterministic # has to use a deterministic encoder with entropy coding to ensure that H[Z|X]=0