defaults:
  - base_H

name: H_hyper_large
mode: H_hyper
kwargs:
  factor_dim: 128
  is_pred_mean: True
  kwargs_ent_bottleneck:
    init_scale: 10 # input should be at initialization in [-init_scale, init_scale]. Larger might create overhead. You can use something like 10 for large images but smaller for smaller 