defaults:
  - base_H

name: H_simclr
is_simclr: True
kwargs:
  is_pred_mean: True
  init_scale: 10 # input should be at initialization in [-init_scale, init_scale]. Larger might create overhead. You can use something like 10 for large images but smaller for smaller 