# @package _global_
defaults:
  - vector

hydra:
  launcher:
    # memory to reserve for the job on each node (in GB)
    mem_gb: 25

    # slurm partition to use on the cluster
    partition: gpu # wsgpu,interactive,cpu,nlp
    exclude: null

    additional_parameters:
      qos: normal # nlp
