defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

experiment: ???
mode: [summarize_metrics] # summarize_RD_curves, plot_all_RD_curves, plot_invariance_RD_curve, plot_scatter_lines, plot_superpose
col_val_subset : {}

kwargs:
  save_dir: ${recolt_data.base_dir}results/${save_experiment}/
  prfx: ""
  dpi: 300
  pretty_renamer: {}
