defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

experiment: ???
agg_mode: [summarize_metrics] # summarize_RD_curves, plot_all_RD_curves, plot_invariance_RD_curve, plot_scatter_lines, plot_superpose
col_val_subset : {}

patterns:
  # name, pattern to find it
  featurizer: "results/exp_${experiment}/**/results_featurizer.csv"
  predictor: "results/exp_${experiment}/**/results_predictor.csv"

collect_data:
  params_to_add: {}

plot_optuna_hypopt:
  storage: sqlite:///${kwargs.base_dir}/results/exp_${experiment}/optuna.db
  study_name: main

kwargs:
  base_dir: ${hydra:runtime.cwd}
  save_dir: results/exp_${experiment}/
  prfx: ""
  dpi: 300
  pretty_renamer: {}
