defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

experiment: ???
agg_mode: [summarize_metrics] # summarize_RD_curves, plot_all_RD_curves, plot_invariance_RD_curve, plot_scatter_lines, plot_superpose
col_val_subset : {}

collect_data:
  # name, pattern to find it
  results: "results/${experiment}/**/results_compression.csv"
  results: "results/${experiment}/**/results_predictor.csv"

kwargs:
  base_dir: ${hydra:runtime.cwd}
  save_dir: results/${experiment}/
  prfx: ""
  dpi: 300
  pretty_renamer: {}
