defaults:
  - main # load all the config that were used for pretraining => makes sure that same model

load_pretrained:
  experiment: ???
  mode: [] # ???
  col_val_subset : {}
  save_dir: ${paths.base_dir}/results/${long_name} # it's not kwargs because will be reevaluated at runtime => can use paths in main
  
  collect_data:
    is_only_feat: True

  reconstruct_image_plot_placeholder: {}
  latent_traversals_plot: {}
  reconstruct_image_plot: {}
  codebook_plot:
      n_pts: 1000

  kwargs:
    prfx: ""
    dpi: 300
    pretty_renamer: {}

# run on cpu
trainer:
  gpus: 0
  precision: 32