# @package _global_

### USER SPECIFIC ###
#! change for your usecase
user: ${oc.env:USER} # automatically change if USER is not defined
wandb_entity: lossyless # team name or user
#####################
