# @package _global_
# like vae (i.e. reconstruction) but for ditributions

loss:
  name: dist_vae
  mode: direct
  
  kwargs: 
      is_classification: False # not classification because regression of inputs

data:
  kwargs:
    dataset_kwargs:
      additional_target: "input"
      n_inputs: 1

decoder:
  out_shape: ${data.shape}