# @package _global_
loss:
  name: gvae
  mode: direct
  kwargs: 
      is_classification: ${data.is_classification_aux}
  
data:
  kwargs:
    dataset_kwargs:
      additional_target:  "representative"
      n_inputs: 1