# @package _global_
loss:
  name: gvib
  mode: direct
  kwargs: 
      is_classification: ${data.is_classification_aux}
  
data:
  kwargs:
    dataset_kwargs:
      additional_target: "max_inv"
      n_inputs: 1