# @package _global_
loss:
  name: taskvib
  mode: direct
  kwargs: 
      is_classification: ${data.is_classification_aux}

data:
  kwargs:
    dataset_kwargs:
      additional_target: target
      n_inputs: 1