# @package _global_
loss:
  name: vib
  mode: direct
  kwargs: 
      is_classification: ${data.is_classification_aux}

data:
  kwargs:
    dataset_kwargs:
      additional_target: "idx"
      n_inputs: 1