# @package _global_
defaults:
  - base@distortion

distortion:
  mode: contrastive
  kwargs:
    is_train_temperature: true # whether to train the temperature (as in CLIP) => removes one hyperparam
    temperature: 0.01 
    is_symmetric: true
    effective_batch_size: ${data.length} # new but seems to work better use `null` if want to deactivate
    is_project: true # strongly recommended
    is_cosine: true # recommended
    project_kwargs:
      mode: mlp
      out_shape: 0.5

data_feat:
  kwargs:
    dataset_kwargs:
      additional_target: equiv_x
