defaults:
  - base

mode: direct
kwargs: 
  z_dim: ${encoder.z_dim}
  y_shape: ${data.aux_shape}
  is_classification: ${data.aux_is_clf}
  dataset: ${data.dataset}
  is_normalized: ${data.kwargs.dataset_kwargs.is_normalize}
  data_mode: ${data.mode}
  arch: null
  arch_kwargs:
    complexity: 2
