# @package _global_
defaults:
  - base@distortion

distortion:
  mode: contrastive
  kwargs:
    temperature: 0.1 
    is_symmetric: true
    effective_batch_size: ${data.length} # new but seems to work better use `null` if want to deactivate
    is_project: true # strongly recommended
    is_cosine: true # recommended
    project_kwargs:
      mode: mlp
      out_shape: 128

data_feat:
  kwargs:
    dataset_kwargs:
      additional_target: equiv_x
