# @package _global_
distortion:
  name: gvib
  mode: direct
  kwargs: 
    z_dim: ${encoder.z_dim}
    y_shape: ${data.target_aux_shape}
    is_classification: ${data.is_classification_aux}
    arch: null
    arch_kwargs:
      complexity: 2
  
data:
  kwargs:
    dataset_kwargs:
      additional_target: "max_inv"