# @package _global_
defaults:
  - ince@distortion

distortion:
  name: ince_text # invariant NCE where equivalence with text
  kwargs:
    temperature: 0.01
    is_cosine: True
    is_project: False
    is_already_featurized: true

encoder:
  z_dim: 512

data_feat:
  kwargs:
    dataset_kwargs:
      base_resize: clip
      equivalence: ["resize","crop"]

data_pred:
  kwargs:
    dataset_kwargs:
      base_resize: clip
      equivalence: ["resize","crop"] 