# @package _global_
defaults:
  - base_direct

distortion:
  name: ivae # VAE reconstructing unaugmented data
  factor_beta: 1 # we use this as standard
  
data:
  kwargs:
    dataset_kwargs:
      additional_target:  "representative"

