# @package _global_
distortion:
  name: ivae # VAE reconstructing unaugmented data
  mode: direct
  kwargs: 
    z_dim: ${encoder.z_dim}
    y_shape: ${data.aux_shape}
    is_classification: ${data.aux_is_clf}
    dataset: ${data.dataset}
    arch: null
    arch_kwargs:
      complexity: 2
  
data:
  kwargs:
    dataset_kwargs:
      additional_target:  "representative"