# @package _global_
distortion:
  name: ivib # VIB predicting the image index
  mode: direct
  factor_beta: 0.01 # compared to ivae gives importance -- to rate 
  kwargs: 
    z_dim: ${encoder.z_dim}
    y_shape: ${data.aux_shape}
    is_classification: ${data.aux_is_clf}
    dataset: ${data.dataset}
    arch: null
    arch_kwargs:
      complexity: 2
  
data:
  kwargs:
    dataset_kwargs:
      additional_target: "max_inv"