# @package _global_
distortion:
  name: ivib # VIB predicting the image index
  mode: direct
  kwargs: 
    z_dim: ${encoder.z_dim}
    y_shape: ${data.aux_shape}
    is_classification: ${data.aux_is_clf}
    arch: null
    arch_kwargs:
      complexity: 2
  
data:
  kwargs:
    dataset_kwargs:
      additional_target: "max_inv"