# @package _global_
defaults:
  - base_direct

distortion:
  name: ivib # VIB predicting the image index
  factor_beta: 0.01 # compared to ivae gives importance -- to rate 
  
data:
  kwargs:
    dataset_kwargs:
      additional_target:  "max_inv"
