# @package _global_
distortion:
  name: nce
  mode: contrastive
  kwargs:
    temperature: 0.1
    is_symmetric: true
    weight: ${data.neg_factor}
  
data:
  kwargs:
    batch_size: 256 # better results with large batch sizes for estimating MI (like 1024 but then you need LARS)
    dataset_kwargs:
      additional_target: other_representative

optimizer:
  is_lars: false # true is uesull if haave to use large batch sizes (but currently bug)
