# @package _global_
defaults:
  - base_direct@distortion

distortion:
  name: taskvib # vib predicting labels
  factor_beta: 0.5
  
data_feat:
  kwargs:
    dataset_kwargs:
      additional_target:  target