# @package _global_
defaults:
  - base_direct

distortion:
  name: vae # vae that reconstructs the augmented images
  factor_beta: 0.5 # distortion is always much larger but you prefer having similar distortion
  
data:
  kwargs:
    dataset_kwargs:
      additional_target:  input
