# @package _global_
defaults:
  - base_direct@distortion

distortion:
  name: VAE # VAE that reconstructs the augmented images
  factor_beta: 0.5 # distortion is always much larger but you prefer having similar distortion
  
data_feat:
  kwargs:
    dataset_kwargs:
      additional_target:  input
