# @package _global_
defaults:
  - base_direct@distortion

distortion:
  name: VIC # VAE reconstructing unaugmented data
  factor_beta: 1 # we use this as standard
  
data_feat:
  kwargs:
    dataset_kwargs:
      additional_target:  "representative"

