# @package _global_

# check that everything is running correctly (single epoch normal)
timeout: 60

trainer:
  weights_summary: top # full to print show the entire model 
  max_epochs: 2
  log_every_n_steps: 10
  # uses 5 % of data
  limit_val_batches: 0.1
  limit_train_batches: 0.05
  limit_test_batches: 0.05

logger:
  wandb:
    tags: [dev]
    anonymous: true

callbacks:
  additional: ["GPUStatsMonitor"] # if add other callbacks through additional will be replaced