# @package _global_

# check that everything is running correctly (2 epochs small data)

timeout: 60

other:
  is_quick: True

trainer:
  max_epochs: 2
  log_every_n_steps: 10
  num_sanity_val_steps: 0 # was giving error
  # uses 5 % of data
  limit_val_batches: 0.2
  limit_train_batches: 0.05
  limit_test_batches: 0.05

data:
  kwargs:
    # use smaller because was giving error
    batch_size: 128
    val_batch_size: 128

logger:
  wandb:
    tags: [dev, quick]
    anonymous: true
    project: tmp

callbacks:
  additional: ["GPUStatsMonitor","LearningRateMonitor"] # if add other callbacks through additional will be replaced