# @package _global_
defaults:
  - base

callbacks:
  ViTFinetuning:
    is_use: true
    kwargs:
      model_name: p_ZlX.mapper.vit
      unfreeze_last_layer: 0
      unfreeze_last_block: 2
      unfreeze_penult_block: 4