# @package _global_
finetune: 
  name: clip
  
callbacks:
  ResnetFinetuning:
    is_use: true
    kwargs:
      resnet_name: p_ZlX.mapper.resnet
      unfreeze_last: 0
      unfreeze_layer4: 2
      unfreeze_layer3: 4
      
      

 
  