# @package _global_
defaults:
  - base
  
finetune: 
  name: simclr

callbacks:
  ResnetFinetuning:
    is_use: true
    kwargs:
      model_name: p_ZlX.mapper.resnet
      unfreeze_last_layer: 0
      unfreeze_last_block: 2
      unfreeze_penult_block: 4