# @package _global_
defaults:
  - base@featurizer

featurizer:
  is_learnable: False 
  quality: null

  loss:
    beta: ${featurizer.quality}


evaluation:
  featurizer:
    ckpt_path: null # has to use current checkpoint (cannot use best because nottrained)