# @package _global_
defaults:
  - neural_feat@featurizer
  - override /architecture@encoder: clip
  - override /distortion: ince_text
  - override /rate: H_hyper
  - override /finetune: clip

featurizer:
  name: bottleneck_clip
  loss:
    beta_anneal: linear

rate:
  kwargs: 
    warmup_k_epoch: 1 # really important to warmup