# @package _global_
defaults:
  - neural_feat@featurizer
  - override /architecture@encoder: simclr
  - override /distortion: ince
  - override /rate: H_simclr

featurizer:
  name: bottleneck_simclr_noanneal

encoder:
  z_dim: 2048

distortion:
  kwargs:
    temperature: 0.1
    is_cosine: True
    is_project: true
    project_kwargs:
      out_shape: 128
      mode: simclr_projector

loss:
  beta_anneal: constant

rate:
  kwargs: 
    warmup_k_epoch: 1 
