# @package _global_
defaults:
  - neural_feat@featurizer
  - override /architecture@encoder: clip
  - override /distortion: ince
  - override /rate: H_hyper
  - override /finetune: clip

data_feat:
  kwargs:
    dataset_kwargs:
      base_resize: clip
      equivalence: ["resize","crop"]

data_pred:
  kwargs:
    dataset_kwargs:
      base_resize: clip
      equivalence: ["resize","crop"] 

featurizer:
  name: bottleneck_clip
  loss:
    beta_anneal: linear

encoder:
  z_dim: 512

distortion:
  kwargs:
    temperature: 0.01
    is_cosine: True
    is_project: False
    is_already_featurized: true

rate:
  kwargs: 
    warmup_k_epoch: 1 # really important to warmup