# @package _global_
defaults:
  - neural_feat@featurizer
  - override /architecture@encoder: simclr
  - override /distortion: ince
  - override /rate: H_hyper

featurizer:
  name: bottleneck_clip

encoder:
  z_dim: 1024

distortion:
  kwargs:
    temperature: 0.01
    weight: 1
    is_cosine: True
    is_project: False

loss:
  beta_anneal: geometric

rate:
  warmup_k_epoch: 1 