# @package _global_
defaults:
  - neural_feat@featurizer
  - override /architecture@encoder: simclr
  - override /distortion: ince
  - override /rate: H_simclr
  - override /finetune: simclr

data_feat:
  kwargs:
    dataset_kwargs:
      base_resize: upscale_crop_eval

data_pred:
  kwargs:
    dataset_kwargs:
      base_resize: upscale_crop_eval

featurizer:
  name: bottleneck_simclr_postproj
  loss:
    beta_anneal: linear

encoder:
  z_dim: 128
  is_post_project: True

distortion:
  kwargs:
    temperature: 0.1
    is_cosine: True
    is_project: false

rate:
  kwargs: 
    warmup_k_epoch: 1 