# @package _global_
defaults:
  - neural_feat@featurizer
  - override /architecture@encoder: simclr
  - override /distortion: ince
  - override /rate: H_simclr
  - override /finetune: simclr

featurizer:
  name: bottleneck_simclr
  loss:
    beta_anneal: geometric

encoder:
  z_dim: 2048

distortion:
  kwargs:
    temperature: 0.1
    is_cosine: True
    is_project: true
    project_kwargs:
      out_shape: 128
      mode: simclr_projector

rate:
  kwargs: 
    warmup_k_epoch: 1 
