# @package _global_
defaults:
  - neural_feat@featurizer
  - override /architecture@encoder: clip
  - override /distortion: lossyZ
  - override /rate: lossless
  - override /finetune: freezer

data_feat:
  kwargs:
    batch_size: 32
    dataset_kwargs:
      base_resize: clip
      equivalence: ["resize","crop"]


update_trainer_feat:
  precision: 32 # need to use precision 32 to make sure that you are not compressing any information

data_pred:
  kwargs:
    dataset_kwargs:
      base_resize: clip
      equivalence: ["resize","crop"]


featurizer:
  name: clip_freeze

encoder:
  z_dim: 512


rate:
  kwargs: 
    is_endToEnd: False # shouldn't be needed becasue already frozen encoder