# @package _global_
defaults:
  - neural_feat@featurizer
  - override /architecture@encoder: simclr
  - override /distortion: ince
  - override /rate: lossless

featurizer:
  name: simclrmini

encoder:
  zdim: 128
  is_post_project: True

distortion:
  kwargs:
    temperature: 0.1
    weight: 1
    is_cosine: True
    is_project: false