# @package _global_
defaults:
  - neural_rec@featurizer # needs @ because you are working in _global_
  - override /rate: H_factorized 
  - override /distortion: vae

featurizer:
  name: vae_hfac_b1
  loss:
    beta: 1