# @package _global_
featurizer:
  name: webp++
  type: webp
  is_learnable: False 
  quality: 70

evaluation:
  is_est_entropies: False # cannot
  featurizer:
    ckpt_path: null # has to use current checkpoint (cannot use best because nottrained)